service: sqstrigger

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1

iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "sqs:ReceiveMessage"
    Resource:
      Fn::GetAtt: [ arn:aws:sqs:sa-east-1:519511952445:CreditCardTransactQueue , Arn ]

functions:
  triggerSQS:
    handler: handler.triggerSQS
    events:
    	# Provide the ARN of your queue
      - sqs: arn:aws:sqs:sa-east-1:519511952445:CreditCardTransactQueue	